// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CalculateRequest struct {
	FirstNum             int32    `protobuf:"varint,1,opt,name=firstNum,proto3" json:"firstNum,omitempty"`
	SecondNum            int32    `protobuf:"varint,2,opt,name=secondNum,proto3" json:"secondNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateRequest) Reset()         { *m = CalculateRequest{} }
func (m *CalculateRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateRequest) ProtoMessage()    {}
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *CalculateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateRequest.Unmarshal(m, b)
}
func (m *CalculateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateRequest.Marshal(b, m, deterministic)
}
func (m *CalculateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateRequest.Merge(m, src)
}
func (m *CalculateRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateRequest.Size(m)
}
func (m *CalculateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateRequest proto.InternalMessageInfo

func (m *CalculateRequest) GetFirstNum() int32 {
	if m != nil {
		return m.FirstNum
	}
	return 0
}

func (m *CalculateRequest) GetSecondNum() int32 {
	if m != nil {
		return m.SecondNum
	}
	return 0
}

type CalculateResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateResponse) Reset()         { *m = CalculateResponse{} }
func (m *CalculateResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateResponse) ProtoMessage()    {}
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *CalculateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateResponse.Unmarshal(m, b)
}
func (m *CalculateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateResponse.Marshal(b, m, deterministic)
}
func (m *CalculateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateResponse.Merge(m, src)
}
func (m *CalculateResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateResponse.Size(m)
}
func (m *CalculateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateResponse proto.InternalMessageInfo

func (m *CalculateResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ManyCalculateRequests struct {
	FirstNum             int32    `protobuf:"varint,1,opt,name=firstNum,proto3" json:"firstNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManyCalculateRequests) Reset()         { *m = ManyCalculateRequests{} }
func (m *ManyCalculateRequests) String() string { return proto.CompactTextString(m) }
func (*ManyCalculateRequests) ProtoMessage()    {}
func (*ManyCalculateRequests) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *ManyCalculateRequests) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManyCalculateRequests.Unmarshal(m, b)
}
func (m *ManyCalculateRequests) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManyCalculateRequests.Marshal(b, m, deterministic)
}
func (m *ManyCalculateRequests) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManyCalculateRequests.Merge(m, src)
}
func (m *ManyCalculateRequests) XXX_Size() int {
	return xxx_messageInfo_ManyCalculateRequests.Size(m)
}
func (m *ManyCalculateRequests) XXX_DiscardUnknown() {
	xxx_messageInfo_ManyCalculateRequests.DiscardUnknown(m)
}

var xxx_messageInfo_ManyCalculateRequests proto.InternalMessageInfo

func (m *ManyCalculateRequests) GetFirstNum() int32 {
	if m != nil {
		return m.FirstNum
	}
	return 0
}

type ManyCalculateResponses struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManyCalculateResponses) Reset()         { *m = ManyCalculateResponses{} }
func (m *ManyCalculateResponses) String() string { return proto.CompactTextString(m) }
func (*ManyCalculateResponses) ProtoMessage()    {}
func (*ManyCalculateResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{3}
}

func (m *ManyCalculateResponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManyCalculateResponses.Unmarshal(m, b)
}
func (m *ManyCalculateResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManyCalculateResponses.Marshal(b, m, deterministic)
}
func (m *ManyCalculateResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManyCalculateResponses.Merge(m, src)
}
func (m *ManyCalculateResponses) XXX_Size() int {
	return xxx_messageInfo_ManyCalculateResponses.Size(m)
}
func (m *ManyCalculateResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_ManyCalculateResponses.DiscardUnknown(m)
}

var xxx_messageInfo_ManyCalculateResponses proto.InternalMessageInfo

func (m *ManyCalculateResponses) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*CalculateRequest)(nil), "calculator.CalculateRequest")
	proto.RegisterType((*CalculateResponse)(nil), "calculator.CalculateResponse")
	proto.RegisterType((*ManyCalculateRequests)(nil), "calculator.ManyCalculateRequests")
	proto.RegisterType((*ManyCalculateResponses)(nil), "calculator.ManyCalculateResponses")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x47, 0x30, 0x0b, 0x92, 0x90, 0x38, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0x5c, 0x08, 0x11, 0x25, 0x1f, 0x2e, 0x01, 0x67, 0x28, 0x2f, 0x35, 0x28,
	0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x8a, 0x8b, 0x23, 0x2d, 0xb3, 0xa8, 0xb8, 0xc4, 0xaf,
	0x34, 0x57, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xce, 0x17, 0x92, 0xe1, 0xe2, 0x2c, 0x4e,
	0x4d, 0xce, 0xcf, 0x4b, 0x01, 0x49, 0x32, 0x81, 0x25, 0x11, 0x02, 0x4a, 0xda, 0x5c, 0x82, 0x48,
	0xa6, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x15, 0xa5, 0x16, 0x97, 0xe6,
	0x94, 0x40, 0x0d, 0x83, 0xf2, 0x94, 0x8c, 0xb9, 0x44, 0x7d, 0x13, 0xf3, 0x2a, 0xd1, 0xad, 0x2f,
	0xc6, 0x67, 0xbf, 0x92, 0x01, 0x97, 0x18, 0x9a, 0x26, 0x88, 0x2d, 0xc5, 0xb8, 0xac, 0x31, 0xda,
	0xc5, 0x88, 0xe4, 0xc5, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x2f, 0x2e, 0x4e, 0xb8,
	0x98, 0x90, 0x8c, 0x1e, 0x52, 0x10, 0xa1, 0x3b, 0x47, 0x4a, 0x16, 0x87, 0x2c, 0xc4, 0x5e, 0x25,
	0x06, 0xa1, 0x28, 0x2e, 0x5e, 0x14, 0x27, 0x09, 0x29, 0x22, 0xeb, 0xc0, 0xea, 0x45, 0x29, 0x25,
	0x3c, 0x4a, 0xa0, 0x1e, 0x52, 0x62, 0x30, 0x60, 0x74, 0xe2, 0x8b, 0xe2, 0x41, 0x8e, 0xcb, 0x24,
	0x36, 0x70, 0x0c, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xfa, 0xed, 0x4f, 0xed, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculateServiceClient is the client API for CalculateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculateServiceClient interface {
	Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error)
	ManyCalculate(ctx context.Context, in *ManyCalculateRequests, opts ...grpc.CallOption) (CalculateService_ManyCalculateClient, error)
}

type calculateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculateServiceClient(cc grpc.ClientConnInterface) CalculateServiceClient {
	return &calculateServiceClient{cc}
}

func (c *calculateServiceClient) Calculate(ctx context.Context, in *CalculateRequest, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculateService/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculateServiceClient) ManyCalculate(ctx context.Context, in *ManyCalculateRequests, opts ...grpc.CallOption) (CalculateService_ManyCalculateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculateService_serviceDesc.Streams[0], "/calculator.CalculateService/ManyCalculate", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculateServiceManyCalculateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculateService_ManyCalculateClient interface {
	Recv() (*ManyCalculateResponses, error)
	grpc.ClientStream
}

type calculateServiceManyCalculateClient struct {
	grpc.ClientStream
}

func (x *calculateServiceManyCalculateClient) Recv() (*ManyCalculateResponses, error) {
	m := new(ManyCalculateResponses)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculateServiceServer is the server API for CalculateService service.
type CalculateServiceServer interface {
	Calculate(context.Context, *CalculateRequest) (*CalculateResponse, error)
	ManyCalculate(*ManyCalculateRequests, CalculateService_ManyCalculateServer) error
}

// UnimplementedCalculateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculateServiceServer struct {
}

func (*UnimplementedCalculateServiceServer) Calculate(ctx context.Context, req *CalculateRequest) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (*UnimplementedCalculateServiceServer) ManyCalculate(req *ManyCalculateRequests, srv CalculateService_ManyCalculateServer) error {
	return status.Errorf(codes.Unimplemented, "method ManyCalculate not implemented")
}

func RegisterCalculateServiceServer(s *grpc.Server, srv CalculateServiceServer) {
	s.RegisterService(&_CalculateService_serviceDesc, srv)
}

func _CalculateService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculateService/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateServiceServer).Calculate(ctx, req.(*CalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculateService_ManyCalculate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ManyCalculateRequests)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculateServiceServer).ManyCalculate(m, &calculateServiceManyCalculateServer{stream})
}

type CalculateService_ManyCalculateServer interface {
	Send(*ManyCalculateResponses) error
	grpc.ServerStream
}

type calculateServiceManyCalculateServer struct {
	grpc.ServerStream
}

func (x *calculateServiceManyCalculateServer) Send(m *ManyCalculateResponses) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculateService",
	HandlerType: (*CalculateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _CalculateService_Calculate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ManyCalculate",
			Handler:       _CalculateService_ManyCalculate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
